export enum TokenType {
  Illegal = 'Illegal',
  Eof = 'Eof',
  Ident = 'Ident',
  Int = 'Int',
  String = 'String',
  Assign = 'Assign',
  Plus = 'Plus',
  Minus = 'Minus',
  Bang = 'Bang',
  Asterisk = 'Asterisk',
  Slash = 'Slash',
  Lt = 'Lt',
  Gt = 'Gt',
  Eq = 'Eq',
  NotEq = 'NotEq',
  Comma = 'Comma',
  Semicolon = 'Semicolon',
  Colon = 'Colon',
  LParen = 'LParen',
  RParen = 'RParen',
  LBrace = 'LBrace',
  RBrace = 'RBrace',
  LBracket = 'LBracket',
  RBracket = 'RBracket',
  Function = 'Function',
  Let = 'Let',
  True = 'True',
  False = 'False',
  If = 'If',
  Else = 'Else',
  Return = 'Return',
  Print = 'Print',
}

export class Token {
  constructor(
    public type: TokenType,
    public literal: string,
    public line: number,
  ) {}
}
